# 多redisTemplate实例配置, 根据名称注入
# 默认配置 hostName: localhost; password: none; port: 6379; database: 0
multi-redis:
  redis-configs:
    redisTemplate0:
      host-name: localhost
      password: 123456
      port: 6379
      database: 0
    redisTemplate1:
      hostName: localhost
      password: 123456
      port: 6379
      database: 1