spring:
  redis:
    host: 127.0.0.1
    password: 123456
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/uaa?useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&useAffectedRows=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver