spring:
  main:
    allow-circular-references: true
  application:
    name: uaa
  profiles:
    active: "@spring.profiles.active@"

jasypt:
  encryptor:
    property:
      prefix: ENC@(
      suffix: )
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

top:
  yousj:
    security:
      uaa: true
    redis:
      spring-cache:
        enable: false
    log:
      aop:
        pointcut: "execution(* top.yousj.uaa.controller..*.*(..))"