spring:
  application:
    name: uaa
  profiles:
    active: "@spring.profiles.active@"

top:
  yousj:
    security:
      uaa: true
    redis:
      spring-cache:
        enable: false
    log:
      aop:
        pointcut: "execution(* top.yousj.uaa.controller..*.*(..))"